#ifndef __TRK8_OPCODE_H
#define __TRK8_OPCODE_H

#include <stdbool.h>

#include "registers.h"

#ifndef TRK8_OPCODE_EXTRACT_BIT_FIELD
    #define TRK8_OPCODE_EXTRACT_BIT_FIELD(_opcode, _mask) (((_opcode) & (_mask)) >> __builtin_ctz((_mask)))
#endif

#ifndef TRK8_OPCODE_CATEGORY_MASK
    #define TRK8_OPCODE_CATEGORY_MASK (0b11000000)
#endif

#ifndef TRK8_OPCODE_NO_OPERANDS_INSTRUCTION_ID_MASK
    #define TRK8_OPCODE_NO_OPERANDS_INSTRUCTION_ID_MASK (0b00111111)
#endif

#ifndef TRK8_OPCODE_ONE_OPERAND_INSTRUCTION_ID_MASK
    #define TRK8_OPCODE_ONE_OPERAND_INSTRUCTION_ID_MASK (0b00110000)
#endif

#ifndef TRK8_OPCODE_TWO_OPERANDS_INSTRUCTION_ID_MASK
    #define TRK8_OPCODE_TWO_OPERANDS_INSTRUCTION_ID_MASK (0b00100000)
#endif

#ifndef TRK8_OPCODE_ONE_OPERAND_SOURCE_REGISTER_ID_MASK
    #define TRK8_OPCODE_ONE_OPERAND_SOURCE_REGISTER_ID_MASK (0b00001111)
#endif

#ifndef TRK8_OPCODE_TWO_OPERANDS_DESTINATION_REGISTER_ID_MASK
    #define TRK8_OPCODE_TWO_OPERANDS_DESTINATION_REGISTER_ID_MASK (0b00011110)
#endif

#ifndef TRK8_OPCODE_TWO_OPERANDS_HAS_IMMEDIATE_OPERAND_MASK
    #define TRK8_OPCODE_TWO_OPERANDS_HAS_IMMEDIATE_OPERAND_MASK (0b00000001)
#endif

#ifndef TRK8_OPCODE_ONE_OPERAND_IMMEDIATE_VALUE_SOURCE
    #define TRK8_OPCODE_ONE_OPERAND_IMMEDIATE_VALUE_SOURCE (0b1111)
#endif

typedef enum _TRK8_OPCODE_CATEGORY {
    TRK8_OPCODE_CATEGORY_NO_OPERANDS,
    TRK8_OPCODE_CATEGORY_ONE_OPERAND,
    TRK8_OPCODE_CATEGORY_TWO_OPERANDS
} trk8_opcode_category_t;

enum __attribute__((packed)) _TRK8_INSTRUCTION_ID_NO_OPERANDS {
    TRK8_INSTRUCTION_ID_NOP = 1,
    TRK8_INSTRUCTION_ID_ADC,
    TRK8_INSTRUCTION_ID_AND,
    TRK8_INSTRUCTION_ID_OR,
    TRK8_INSTRUCTION_ID_NOT,
    TRK8_INSTRUCTION_ID_CMP,
    TRK8_INSTRUCTION_ID_JMP,
    TRK8_INSTRUCTION_ID_BNE,
    TRK8_INSTRUCTION_ID_BCA,
    TRK8_INSTRUCTION_ID_BZE,
    TRK8_INSTRUCTION_ID_HLT
};

enum __attribute__((packed)) _TRK8_INSTRUCTION_ID_ONE_OPERAND {
    TRK8_INSTRUCTION_ID_STB,
    TRK8_INSTRUCTION_ID_LDB,
    TRK8_INSTRUCTION_ID_PUSH,
    TRK8_INSTRUCTION_ID_POP
};

enum __attribute__((packed)) _TRK8_INSTRUCTION_ID_TWO_OPERANDS {
    TRK8_INSTRUCTION_ID_MOV
};

typedef struct _TRK8_OPCODE {
    trk8_opcode_category_t category;

    union _OPCODE_INSTRUCTION_ID {
        enum _TRK8_INSTRUCTION_ID_NO_OPERANDS no_operands_id;
        enum _TRK8_INSTRUCTION_ID_ONE_OPERAND one_operand_id;
        enum _TRK8_INSTRUCTION_ID_TWO_OPERANDS two_operands_id;
    } instruction_id;

    trk8_register_id_t register_id;

    bool has_immediate_operand;
} trk8_opcode_t;

#endif